version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    image: node:7
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./angular-client:/opt/angular-client
    working_dir: /opt/angular-client
    command: npm start

  express: #name of the second service
    image: node:7
    ports:
      - "3000:3000" #specify ports forewarding
      - "9229:9229" #specify ports forewarding
    links:
      - database # link this service to the database service
    volumes:
      - ./express-server:/opt/express-server
    working_dir: /opt/express-server
    command: npm start

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" #specify ports forewarding
